<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>comment</key>
		<string>Gal2Renpy for Sublime</string>
		<key>fileTypes</key>
		<array>
			<string>g</string>
			<string>gal</string>
		</array>
		<key>foldingStartMarker</key>
		<string>(begin)\s*(//.*)?$</string>
		<key>foldingStopMarker</key>
		<string>^\s*(end)$</string>		
		<key>name</key>
		<string>Gal2Renpy</string>
		<key>patterns</key>
		<array>
			<!-- module XXX -->
			<dict>
				<key>begin</key>
				<string>(?=\S+\s【.*】)</string>
				<key>end</key>
				<string>\n</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>(\S+)\s(【).*(】)</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string></string>
							</dict>
						</dict>
					</dict>
				</array>
				<key>name</key>
				<string>meta.function.Gal2Renpy</string>
			</dict>
			<dict>
				<key>begin</key>
				<string>(#)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>comment</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\n</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>(.*)</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>comment</string>
							</dict>
						</dict>
					</dict>
				</array>
				<key>name</key>
				<string>meta.function.Gal2Renpy</string>
			</dict>

			<dict>
				<key>begin</key>
				<string>(?x)
					(&lt;(sc|sw|ch|bg|bgm|sound|data|cg|vd|ef|gf|key|mode|view|chc|hpc|renpy|messadd|chr|test)(?=&gt;))
				</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.control.Gal2Renpy</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(?=&gt;)</string>
				<key>endCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.control.Gal2Renpy</string>
					</dict>
				</dict>
			</dict>

			<dict>
				<key>begin</key>
				<string>(?x)
					(&lt;(sc|sw|ch|bg|bgm|sound|data|cg|vd|ef|gf|key|mode|view|chc|hpc|renpy|messadd|chr|test)\s+)
				</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.control.Gal2Renpy</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(?=&gt;)</string>
				<key>endCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.control.Gal2Renpy</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>([a-z]+:)(.*?)(?=&gt;|[a-z]+:)</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>storage.type.Gal2Renpy</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>string.Gal2Renpy</string>
							</dict>
						</dict>
					</dict>
				</array>
			</dict>

			<dict>
				<key>begin</key>
				<string>(?x)
					(&lt;/(sc|sw|ch|bg|bgm|sound|data|cg|vd|ef|gf|key|mode|view|chc|hpc|renpy|messadd|chr|test)(?=&gt;))
				</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.control.Gal2Renpy</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(&gt;)</string>
				<key>endCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.control.Gal2Renpy</string>
					</dict>
				</dict>
			</dict>

			<dict>
				<key>begin</key>
				<string>(?x)
					((?!&lt;/S+)&gt;)
				</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.control.Gal2Renpy</string>
					</dict>
				</dict>
				<key>end</key>
				<string>(?=&lt;)</string>
				<key>endCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>entity.name.function.Gal2Renpy</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>([a-z]+:)(.*?)(?=&lt;|\n|[a-z]+:)</string>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>storage.type.Gal2Renpy</string>
							</dict>
							<key>2</key>
							<dict>
								<key>name</key>
								<string>string.Gal2Renpy</string>
							</dict>
						</dict>
					</dict>
				</array>
			</dict>

		</array>
		<key>scopeName</key>
		<string>source.Gal2Renpy</string>
		<key>uuid</key>
		<string>6856ea09-6f82-3ead-a3ae-2dd2d81453bf</string>
	</dict>
</plist>